apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: let-him-cook
spec:
  type: Standalone
  persistent: true
  exposedExternally: true



# apiVersion: mongodb.com/v1
# kind: MongoDB
# metadata:
#   name: mongodb
# spec:
#   version: "4.2.2-ent"
#   # opsManager:
#     # configMapRef:
#     #   name: <configMap.metadata.name>
#             # Must match metadata.name in ConfigMap file
#   # credentials: <mycredentials>
#   type: Standalone
#   persistent: true


# # apiVersion: apps/v1
# # kind: PersistentVolumeClaim
# # metadata:
# #   name: mongodb-deployment
# # spec:
# #   replicas: 1
# #   selector:
# #     matchLabels:
# #       app: mongodb
# #   template:
# #     metadata:
# #       labels:
# #         app: mongodb
# #     spec:
# #       containers:
# #         - name: mongodb
# #           image: texasimages.azurecr.io/mongo
# #           ports:
# #             - containerPort: 27017
# #           volumeMounts:
# #             - name: mongodb-persistent-storage
# #               mountPath: /data/db
# #         volumes:
# #           - name: mongodb-persistent-storage
# #             persistentVolumeClaim:
# #               claimName: mongodb-pvc